apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  containers:
  - image: phpmyadmin
    name: phpmyadmin
    ports:
    - containerPort: 80
    env:
    - name: PMA_HOST
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: mysql-service
    - name: PMA_PORT
      value: '3306'
