apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql-db
spec:
  containers:
  - image: mysql
    name: mysql-db
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-vol
      mountPath: /var/lib/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secrets
          key: mysql-root
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: secrets
          key: mysql-user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secrets
          key: mysql-password
  volumes:
  - name: mysql-vol
    persistentVolumeClaim:
      claimName: mysql-pvc
