apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-namespace
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-internal
  namespace: jenkins-namespace
spec:
  type: ClusterIP
  selector:
    app: jenkins-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000
